apiVersion: 1

datasources:
  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s

  # InfluxDB for time series data
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: trading_metrics
    user: trading_user
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}
    jsonData:
      httpMode: GET
      timeInterval: 10s

  # Elasticsearch for logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[logstash-]YYYY.MM.DD"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 8

  # PostgreSQL for application data
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: trading_db
    user: trading_user
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400

  # Redis for cache metrics
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0